In [ ]:
# pandas is data manipulation,data cleaning,data mining
# pandas there two concepts 1.Series
                          #  2.Data Frame
    
# 1.series is one dimension
#2.Data Frame is a Multiple Dimension its work on Execl sheet

In [4]:
import numpy as np
import pandas as pd

In [7]:
a=pd.Series(np.arange(1,10))
print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32
<class 'pandas.core.series.Series'>


In [8]:
x=pd.Series(np.arange(1,31))
print(type(x))
print(x)
print(x.shape)
print(x.size)

<class 'pandas.core.series.Series'>
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
dtype: int32
(30,)
30


In [9]:
a=pd.Series([10,30,50,70,90],index=['a','b','c','d','e'])
print(a)

a    10
b    30
c    50
d    70
e    90
dtype: int64


In [10]:
a['b']

30

In [11]:
a=pd.Series([10,30,50,70,90],index=['r1','r2','r3','r4','r5'])
print(a)

r1    10
r2    30
r3    50
r4    70
r5    90
dtype: int64


In [12]:
a['r4']

70

In [13]:
# data Frame
a=np.arange(1,101).reshape(10,10)
print(a)
print(type(a))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
<class 'numpy.ndarray'>


In [14]:
print(a[4][0])

41


In [15]:
print(a[5][4])

55


In [20]:
a=pd.DataFrame(np.arange(1,101).reshape(10,10))
a

0   1   2   3   4   5   6   7   8    9
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [1]:
a=pd.DataFrame(np.arange(1,21).reshape(5,4),columns=['name','age','salary','Domain'],index=['a','b','c','d','e'])
a

NameError: name 'pd' is not defined

In [2]:
x={'age':[25,55,67,88],'salary':[12000,15000,17000,19000],'location':['hyd','delhi','Banglore','pune']}
print(x)


{'age': [25, 55, 67, 88], 'salary': [12000, 15000, 17000, 19000], 'location': ['hyd', 'delhi', 'Banglore', 'pune']}


In [8]:
b=pd.DataFrame(x)
b

age  salary  location
0   25   12000       hyd
1   55   15000     delhi
2   67   17000  Banglore
3   88   19000      pune

In [9]:
b['location'][2]

'Banglore'

In [10]:
b['salary'][1]

15000

In [11]:
b['age'][3]

88

In [12]:
df=pd.read_csv('http://localhost:8888/edit/Downloads/Titanic-Dataset.csv')
df

ParserError: Error tokenizing data. C error: Expected 1 fields in line 12, saw 2


In [1]:
# numpy is a numerical Python
# numpy work on Dimension data
# pandas is a data manipulation,data cleaning,data mininig

In [2]:
import numpy as np
import pandas as pd

In [3]:
# series - one dimenision
a=np.arange(1,11)
print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)
1


In [4]:
a=pd.Series(np.arange(1,11))
print(a)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int32


In [6]:
x=pd.Series(np.arange(2,21))
print(x)

0      2
1      3
2      4
3      5
4      6
5      7
6      8
7      9
8     10
9     11
10    12
11    13
12    14
13    15
14    16
15    17
16    18
17    19
18    20
dtype: int32


In [7]:
x=pd.Series([1,4,7,9],index=['a1','a2','a3','a4'])
print(x)

a1    1
a2    4
a3    7
a4    9
dtype: int64


In [8]:
x['a3']

7

In [10]:
# dataframe is a multiple dimenisions
b=pd.DataFrame(np.arange(1,71).reshape(10,7))
b

0   1   2   3   4   5   6
0   1   2   3   4   5   6   7
1   8   9  10  11  12  13  14
2  15  16  17  18  19  20  21
3  22  23  24  25  26  27  28
4  29  30  31  32  33  34  35
5  36  37  38  39  40  41  42
6  43  44  45  46  47  48  49
7  50  51  52  53  54  55  56
8  57  58  59  60  61  62  63
9  64  65  66  67  68  69  70

In [15]:
a=pd.DataFrame(np.arange(1,81).reshape(10,8))
a

0   1   2   3   4   5   6   7
0   1   2   3   4   5   6   7   8
1   9  10  11  12  13  14  15  16
2  17  18  19  20  21  22  23  24
3  25  26  27  28  29  30  31  32
4  33  34  35  36  37  38  39  40
5  41  42  43  44  45  46  47  48
6  49  50  51  52  53  54  55  56
7  57  58  59  60  61  62  63  64
8  65  66  67  68  69  70  71  72
9  73  74  75  76  77  78  79  80

In [2]:
a=pd.Series(np.arange(1,10))
print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32
<class 'pandas.core.series.Series'>


In [3]:
x=pd.Series(np.arange(20,40))
print(x)
print(type(x))

0     20
1     21
2     22
3     23
4     24
5     25
6     26
7     27
8     28
9     29
10    30
11    31
12    32
13    33
14    34
15    35
16    36
17    37
18    38
19    39
dtype: int32
<class 'pandas.core.series.Series'>


In [5]:
y=pd.Series([10,40,60,90],index=['a1','a2','a3','a4'])
print(y)
print(type(y))

a1    10
a2    40
a3    60
a4    90
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
z=pd.Series([1,4,8,10,12],index=['r1','r2','r3','r4','r5'])
print(z)
print(type(z))

r1     1
r2     4
r3     8
r4    10
r5    12
dtype: int64
<class 'pandas.core.series.Series'>


In [7]:
z['r4']

10

In [8]:
z['r5']

12

In [9]:
z['r1':'r3']

r1    1
r2    4
r3    8
dtype: int64

In [17]:
# data frame is used to multiple data in excel sheet
a=pd.DataFrame(np.arange(1,101).reshape(10,10))
a

0   1   2   3   4   5   6   7   8    9
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [20]:
x=pd.DataFrame(np.arange(1,51).reshape(10,5))
x

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30
6  31  32  33  34  35
7  36  37  38  39  40
8  41  42  43  44  45
9  46  47  48  49  50

In [21]:
a = pd.DataFrame(np.arange(1,21).reshape(5,4) , columns=['A','sai','kiran','kkkk'] , index = ['a','b','c','d','e'])
a

A  sai  kiran  kkkk
a   1    2      3     4
b   5    6      7     8
c   9   10     11    12
d  13   14     15    16
e  17   18     19    20

In [5]:
a = {'Age':[10,11,15,20] , 'salary':[100,200,300,500] , 'location':['hyd','chennai','bangalore','UK'],'Domain':['CSE','ECE','MECH','CIVIL']}
print(a)

{'Age': [10, 11, 15, 20], 'salary': [100, 200, 300, 500], 'location': ['hyd', 'chennai', 'bangalore', 'UK'], 'Domain': ['CSE', 'ECE', 'MECH', 'CIVIL']}


In [6]:
x=pd.DataFrame(a)
x

Age  salary   location Domain
0   10     100        hyd    CSE
1   11     200    chennai    ECE
2   15     300  bangalore   MECH
3   20     500         UK  CIVIL

In [7]:
x['location'][3]

'UK'

In [9]:
x['salary'][2]

300

In [10]:
x.loc[1:,:'location']

Age  salary   location
1   11     200    chennai
2   15     300  bangalore
3   20     500         UK

In [12]:
x.loc[2:,:'salary']

Age  salary
2   15     300
3   20     500

In [16]:
x.loc[1:4,'Age':'Domain']

Age  salary   location Domain
1   11     200    chennai    ECE
2   15     300  bangalore   MECH
3   20     500         UK  CIVIL

In [18]:
x.iloc[1:3,1:3]

salary   location
1     200    chennai
2     300  bangalore